### PR TITLE
replaced arp with ip on linux (arp is deprecated). 'arp -a' -> 'ip n'…

### PR DESCRIPTION
**Pull request by lucafornerone**
replaced arp with ip on linux (arp is deprecated). searching for devices on linux is now faster.

### CODE REVIEW

**Comment by natterstefan** [comment]
Hi @lucafornerone, thanks for the PR. Looks like for some reason the checks do not run on this PR. Strange. Can you verify that the tests still pass, after this change, please?

**Comment by lucafornerone** [comment]
hi @natterstefan! yes, sorry. I'll make a comkit when it's all right.

**Comment by lucafornerone** [comment]
It's ready. I had to adapt linux tests, 'arp' output is a little bit different from 'ip' output.

**Comment by DylanPiercey** [comment]
To be clear this would be a breaking change right?

**Comment by lucafornerone** [comment]
right.

**Pull request closed without merging**
