### PR TITLE
chore: updated (dev)Dependencies and node version

### PR DESCRIPTION
**Pull request by natterstefan**
FYI: Node 8 reaches EOL on December 2019 (https://github.com/nodejs/Release#release-schedule)

### CODE REVIEW

**Comment by natterstefan** [comment]
@DylanPiercey most likely this should be a breaking change because we change the required node-version. What do you think?

**Comment by DylanPiercey** [comment]
Yeah this should be a major. That is fine with me though.

**Comment by natterstefan** [comment]
@DylanPiercey perfect, shall we deploy the current unreleased changes with this new major or as a 2.x feature, before creating this major? https://github.com/DylanPiercey/local-devices/blob/master/CHANGES.md#unreleased.

**Comment by DylanPiercey** [comment]
Sorry for the delay. I think let's just go ahead and release the unreleased changes with the next major.

Would you like to do the release?

**Comment by natterstefan** [comment]
@DylanPiercey easy, then let's do it all together. Sure, I can do it. Do you mean on npm and/or here?

**Comment by DylanPiercey** [comment]
Both 😄

**Comment by natterstefan** [comment]
:D

Sure, I just need publish rights on npm, please. Here's my user: https://www.npmjs.com/~natterstefan.

**Comment by DylanPiercey** [comment]
Added! Thanks 😄

**Comment by natterstefan** [comment]
Thank you, will publish it in a few minutes.

**Pull request merged**
